print("Summit Atlas — SC811 Ticket Scanner")
print("-----------------------------------")
print("SC811 scanner placeholder active.")
print("Future source: SC811 / Exactix ticket data")
print("Scan complete.")